# bilge_khagan_slide_east.py
#
# Copyright 2022-2023 imsi32
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

from gi.repository import Adw
from gi.repository import Gtk


@Gtk.Template(resource_path='/com/github/imsi32/RooTi/inscriptions/bilge_khagan/bilge_khagan_slide_east.ui')
class BilgeKhaganSlideEast(Adw.Bin):
    __gtype_name__ = 'BilgeKhaganSlideEast'

    old_BK_E1 = Gtk.Template.Child("old_BK_E1")
    old_BK_E2 = Gtk.Template.Child("old_BK_E2")
    old_BK_E3 = Gtk.Template.Child("old_BK_E3")
    old_BK_E4 = Gtk.Template.Child("old_BK_E4")
    old_BK_E5 = Gtk.Template.Child("old_BK_E5")
    old_BK_E6 = Gtk.Template.Child("old_BK_E6")
    old_BK_E7 = Gtk.Template.Child("old_BK_E7")
    old_BK_E8 = Gtk.Template.Child("old_BK_E8")
    old_BK_E9 = Gtk.Template.Child("old_BK_E9")
    old_BK_E10 = Gtk.Template.Child("old_BK_E10")
    old_BK_E11 = Gtk.Template.Child("old_BK_E11")
    old_BK_E12 = Gtk.Template.Child("old_BK_E12")
    old_BK_E13 = Gtk.Template.Child("old_BK_E13")
    old_BK_E14 = Gtk.Template.Child("old_BK_E14")
    old_BK_E15 = Gtk.Template.Child("old_BK_E15")
    old_BK_E16 = Gtk.Template.Child("old_BK_E16")
    old_BK_E17 = Gtk.Template.Child("old_BK_E17")
    old_BK_E18 = Gtk.Template.Child("old_BK_E18")
    old_BK_E19 = Gtk.Template.Child("old_BK_E19")
    old_BK_E20 = Gtk.Template.Child("old_BK_E20")
    old_BK_E21 = Gtk.Template.Child("old_BK_E21")
    old_BK_E22 = Gtk.Template.Child("old_BK_E22")
    old_BK_E23 = Gtk.Template.Child("old_BK_E23")
    old_BK_E24 = Gtk.Template.Child("old_BK_E24")
    old_BK_E25 = Gtk.Template.Child("old_BK_E25")
    old_BK_E26 = Gtk.Template.Child("old_BK_E26")
    old_BK_E27 = Gtk.Template.Child("old_BK_E27")
    old_BK_E28 = Gtk.Template.Child("old_BK_E28")
    old_BK_E29 = Gtk.Template.Child("old_BK_E29")
    old_BK_E30 = Gtk.Template.Child("old_BK_E30")
    old_BK_E31 = Gtk.Template.Child("old_BK_E31")
    old_BK_E32 = Gtk.Template.Child("old_BK_E32")
    old_BK_E33 = Gtk.Template.Child("old_BK_E33")
    old_BK_E34 = Gtk.Template.Child("old_BK_E34")
    old_BK_E35 = Gtk.Template.Child("old_BK_E35")
    old_BK_E36 = Gtk.Template.Child("old_BK_E36")
    old_BK_E37 = Gtk.Template.Child("old_BK_E37")
    old_BK_E38 = Gtk.Template.Child("old_BK_E38")
    old_BK_E39 = Gtk.Template.Child("old_BK_E39")
    old_BK_E40 = Gtk.Template.Child("old_BK_E40")
    old_BK_E41 = Gtk.Template.Child("old_BK_E41")

    pho_BK_E1 = Gtk.Template.Child("pho_BK_E1")
    pho_BK_E2 = Gtk.Template.Child("pho_BK_E2")
    pho_BK_E3 = Gtk.Template.Child("pho_BK_E3")
    pho_BK_E4 = Gtk.Template.Child("pho_BK_E4")
    pho_BK_E5 = Gtk.Template.Child("pho_BK_E5")
    pho_BK_E6 = Gtk.Template.Child("pho_BK_E6")
    pho_BK_E7 = Gtk.Template.Child("pho_BK_E7")
    pho_BK_E8 = Gtk.Template.Child("pho_BK_E8")
    pho_BK_E9 = Gtk.Template.Child("pho_BK_E9")
    pho_BK_E10 = Gtk.Template.Child("pho_BK_E10")
    pho_BK_E11 = Gtk.Template.Child("pho_BK_E11")
    pho_BK_E12 = Gtk.Template.Child("pho_BK_E12")
    pho_BK_E13 = Gtk.Template.Child("pho_BK_E13")
    pho_BK_E14 = Gtk.Template.Child("pho_BK_E14")
    pho_BK_E15 = Gtk.Template.Child("pho_BK_E15")
    pho_BK_E16 = Gtk.Template.Child("pho_BK_E16")
    pho_BK_E17 = Gtk.Template.Child("pho_BK_E17")
    pho_BK_E18 = Gtk.Template.Child("pho_BK_E18")
    pho_BK_E19 = Gtk.Template.Child("pho_BK_E19")
    pho_BK_E20 = Gtk.Template.Child("pho_BK_E20")
    pho_BK_E21 = Gtk.Template.Child("pho_BK_E21")
    pho_BK_E22 = Gtk.Template.Child("pho_BK_E22")
    pho_BK_E23 = Gtk.Template.Child("pho_BK_E23")
    pho_BK_E24 = Gtk.Template.Child("pho_BK_E24")
    pho_BK_E25 = Gtk.Template.Child("pho_BK_E25")
    pho_BK_E26 = Gtk.Template.Child("pho_BK_E26")
    pho_BK_E27 = Gtk.Template.Child("pho_BK_E27")
    pho_BK_E28 = Gtk.Template.Child("pho_BK_E28")
    pho_BK_E29 = Gtk.Template.Child("pho_BK_E29")
    pho_BK_E30 = Gtk.Template.Child("pho_BK_E30")
    pho_BK_E31 = Gtk.Template.Child("pho_BK_E31")
    pho_BK_E32 = Gtk.Template.Child("pho_BK_E32")
    pho_BK_E33 = Gtk.Template.Child("pho_BK_E33")
    pho_BK_E34 = Gtk.Template.Child("pho_BK_E34")
    pho_BK_E35 = Gtk.Template.Child("pho_BK_E35")
    pho_BK_E36 = Gtk.Template.Child("pho_BK_E36")
    pho_BK_E37 = Gtk.Template.Child("pho_BK_E37")
    pho_BK_E38 = Gtk.Template.Child("pho_BK_E38")
    pho_BK_E39 = Gtk.Template.Child("pho_BK_E39")
    pho_BK_E40 = Gtk.Template.Child("pho_BK_E40")
    pho_BK_E41 = Gtk.Template.Child("pho_BK_E41")

    mod_BK_E1 = Gtk.Template.Child("mod_BK_E1")
    mod_BK_E2 = Gtk.Template.Child("mod_BK_E2")
    mod_BK_E3 = Gtk.Template.Child("mod_BK_E3")
    mod_BK_E4 = Gtk.Template.Child("mod_BK_E4")
    mod_BK_E5 = Gtk.Template.Child("mod_BK_E5")
    mod_BK_E6 = Gtk.Template.Child("mod_BK_E6")
    mod_BK_E7 = Gtk.Template.Child("mod_BK_E7")
    mod_BK_E8 = Gtk.Template.Child("mod_BK_E8")
    mod_BK_E9 = Gtk.Template.Child("mod_BK_E9")
    mod_BK_E10 = Gtk.Template.Child("mod_BK_E10")
    mod_BK_E11 = Gtk.Template.Child("mod_BK_E11")
    mod_BK_E12 = Gtk.Template.Child("mod_BK_E12")
    mod_BK_E13 = Gtk.Template.Child("mod_BK_E13")
    mod_BK_E14 = Gtk.Template.Child("mod_BK_E14")
    mod_BK_E15 = Gtk.Template.Child("mod_BK_E15")
    mod_BK_E16 = Gtk.Template.Child("mod_BK_E16")
    mod_BK_E17 = Gtk.Template.Child("mod_BK_E17")
    mod_BK_E18 = Gtk.Template.Child("mod_BK_E18")
    mod_BK_E19 = Gtk.Template.Child("mod_BK_E19")
    mod_BK_E20 = Gtk.Template.Child("mod_BK_E20")
    mod_BK_E21 = Gtk.Template.Child("mod_BK_E21")
    mod_BK_E22 = Gtk.Template.Child("mod_BK_E22")
    mod_BK_E23 = Gtk.Template.Child("mod_BK_E23")
    mod_BK_E24 = Gtk.Template.Child("mod_BK_E24")
    mod_BK_E25 = Gtk.Template.Child("mod_BK_E25")
    mod_BK_E26 = Gtk.Template.Child("mod_BK_E26")
    mod_BK_E27 = Gtk.Template.Child("mod_BK_E27")
    mod_BK_E28 = Gtk.Template.Child("mod_BK_E28")
    mod_BK_E29 = Gtk.Template.Child("mod_BK_E29")
    mod_BK_E30 = Gtk.Template.Child("mod_BK_E30")
    mod_BK_E31 = Gtk.Template.Child("mod_BK_E31")
    mod_BK_E32 = Gtk.Template.Child("mod_BK_E32")
    mod_BK_E33 = Gtk.Template.Child("mod_BK_E33")
    mod_BK_E34 = Gtk.Template.Child("mod_BK_E34")
    mod_BK_E35 = Gtk.Template.Child("mod_BK_E35")
    mod_BK_E36 = Gtk.Template.Child("mod_BK_E36")
    mod_BK_E37 = Gtk.Template.Child("mod_BK_E37")
    mod_BK_E38 = Gtk.Template.Child("mod_BK_E38")
    mod_BK_E39 = Gtk.Template.Child("mod_BK_E39")
    mod_BK_E40 = Gtk.Template.Child("mod_BK_E40")
    mod_BK_E41 = Gtk.Template.Child("mod_BK_E41")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
